#!MC 1410
$!VarSet |MFBD| = 'C:\Program Files\Tecplot\Tecplot 360 EX 2016 R2'
$!SLICELAYERS SHOW = YES
$!SLICEATTRIBUTES 1  SLICESURFACE = YPLANES
$!SLICEATTRIBUTES 1  PRIMARYPOSITION{Y = 0.5}
$!SETCONTOURVAR
  VAR = 5
  CONTOURGROUP = 1
$!CONTOURLEVELS NEW
  CONTOURGROUP = 1
  RAWDATA
17
0.0
10.0
20.0
30.0
40.0
50.0
60.0
70.0
80.0
90.0
100.0
110.0
120.0
130.0
140.0
150.0
160.0
$!GLOBALCONTOUR 1  LEGEND{ISVERTICAL = YES}
$!GLOBALCONTOUR 1  LABELS{AUTOLEVELSKIP = 1}
$!GLOBALCONTOUR 1  LEGEND{ROWSPACING = 1.2}
$!GLOBALCONTOUR 1
LEGEND
{
SHOW = YES
XYPOS
{
X = 35
Y = 45
}
}
$!GLOBALCONTOUR 1  COLORMAPNAME = 'Modern'
$!GLOBALCONTOUR 1  COLORMAPFILTER{COLORMAPDISTRIBUTION = CONTINUOUS}
$!GLOBALCONTOUR 1  COLORMAPFILTER{CONTINUOUSCOLOR{CMIN = 20}}
$!GLOBALCONTOUR 1  COLORMAPFILTER{CONTINUOUSCOLOR{CMAX = 140}}
$!CREATESLICEZONES
$!FIELDLAYERS SHOWCONTOUR = YES
$!PLOTTYPE = CARTESIAN2D
$!TWODAXIS XDETAIL{VARNUM = 1}
$!TWODAXIS YDETAIL{VARNUM = 3}
$!ACTIVEFIELDMAPS = [2]
$!EXPORTSETUP EXPORTFNAME = 'pic.png'
$!EXPORT
  EXPORTREGION = CURRENTFRAME
$!DELETEZONES [2]
$!PLOTTYPE = CARTESIAN3D
$!RemoveVar |MFBD|
$!Quit